//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_payable
    {
        public int id { get; set; }
        public int purchaseOrder { get; set; }
        public int supplier { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> outstanding_balance { get; set; }
        public string state { get; set; }
        public string made_by { get; set; }
    
        public virtual purchaseOrder purchaseOrder1 { get; set; }
        public virtual supplier supplier1 { get; set; }
    }
}
