//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class accounts_receivable
    {
        public int id { get; set; }
        public int bill { get; set; }
        public int client { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> outstanding_balance { get; set; }
        public string credit_time { get; set; }
        public string date { get; set; }
        public string state { get; set; }
        public string made_by { get; set; }
    
        public virtual bill bill1 { get; set; }
        public virtual client client1 { get; set; }
    }
}
