//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class bills
    {
        public bills()
        {
            this.accounts_payable = new HashSet<accounts_payable>();
            this.accounts_receivable = new HashSet<accounts_receivable>();
            this.sales_history = new HashSet<sales_history>();
            this.requisition = new HashSet<requisition>();
        }
    
        public int bill_id { get; set; }
        public int id_client { get; set; }
        public string person_name { get; set; }
        public Nullable<System.DateTime> present_date { get; set; }
        public string ddescription { get; set; }
        public string payment_term { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> amount_total { get; set; }
        public Nullable<int> total_taxes { get; set; }
        public Nullable<int> total_withTaxes { get; set; }
        public string sstate { get; set; }
    
        public virtual ICollection<accounts_payable> accounts_payable { get; set; }
        public virtual ICollection<accounts_receivable> accounts_receivable { get; set; }
        public virtual ICollection<sales_history> sales_history { get; set; }
        public virtual ICollection<requisition> requisition { get; set; }
        public virtual clients clients { get; set; }
        public virtual products products { get; set; }
    }
}
