//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.accounts_receivable = new HashSet<accounts_receivable>();
            this.bill = new HashSet<bill>();
            this.requisition = new HashSet<requisition>();
        }
    
        public int id { get; set; }
        public string identification { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
    
        public virtual ICollection<accounts_receivable> accounts_receivable { get; set; }
        public virtual ICollection<bill> bill { get; set; }
        public virtual ICollection<requisition> requisition { get; set; }
    }
}
