//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class clients
    {
        public clients()
        {
            this.accounts_receivable = new HashSet<accounts_receivable>();
            this.bills = new HashSet<bills>();
            this.route_s = new HashSet<route_s>();
            this.sales_history = new HashSet<sales_history>();
        }
    
        public int client_id { get; set; }
        public string id_person { get; set; }
        public string delivery_address { get; set; }
    
        public virtual ICollection<accounts_receivable> accounts_receivable { get; set; }
        public virtual ICollection<bills> bills { get; set; }
        public virtual ICollection<route_s> route_s { get; set; }
        public virtual ICollection<sales_history> sales_history { get; set; }
    }
}
