//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEES
    {
        public EMPLOYEES()
        {
            this.route_s = new HashSet<route_s>();
            this.requisition_type = new HashSet<requisition_type>();
        }
    
        public string identification { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> age { get; set; }
        public string license { get; set; }
        public string password1 { get; set; }
        public string phone { get; set; }
        public Nullable<int> postType { get; set; }
        public Nullable<double> salary { get; set; }
        public string a_ddress { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<route_s> route_s { get; set; }
        public virtual ICollection<requisition_type> requisition_type { get; set; }
    }
}
