//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        public EMPLOYEE()
        {
            this.requisition = new HashSet<requisition>();
        }
    
        public int id { get; set; }
        public string identification { get; set; }
        public string name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> age { get; set; }
        public string license { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
        public Nullable<int> postType { get; set; }
        public Nullable<int> salary { get; set; }
        public string address { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<requisition> requisition { get; set; }
        public virtual postType postType1 { get; set; }
    }
}
