//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class family_product
    {
        public family_product()
        {
            this.products = new HashSet<products>();
        }
    
        public int family_code { get; set; }
        public string familyProduct_name { get; set; }
    
        public virtual ICollection<products> products { get; set; }
    }
}
