//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public products()
        {
            this.bills = new HashSet<bills>();
            this.sales_history = new HashSet<sales_history>();
            this.requisition = new HashSet<requisition>();
        }
    
        public int product_id { get; set; }
        public int familyProduct_code { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<double> unit_price { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<int> existence { get; set; }
        public Nullable<int> minimum_num { get; set; }
        public string sstate { get; set; }
        public string unitMeasure { get; set; }
        public int majorSupplier_id { get; set; }
    
        public virtual ICollection<bills> bills { get; set; }
        public virtual family_product family_product { get; set; }
        public virtual ICollection<sales_history> sales_history { get; set; }
        public virtual ICollection<requisition> requisition { get; set; }
        public virtual suppliers suppliers { get; set; }
    }
}
