//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public requisition()
        {
            this.route_s = new HashSet<route_s>();
        }
    
        public int requisition_id { get; set; }
        public int requisition_type { get; set; }
        public int product_code { get; set; }
        public Nullable<int> quantity_toBuy { get; set; }
        public string description { get; set; }
        public string order_priority { get; set; }
        public string state { get; set; }
        public Nullable<int> bill_code { get; set; }
    
        public virtual bills bills { get; set; }
        public virtual products products { get; set; }
        public virtual ICollection<route_s> route_s { get; set; }
        public virtual requisition_type requisition_type1 { get; set; }
    }
}
