//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition_type
    {
        public requisition_type()
        {
            this.requisition = new HashSet<requisition>();
        }
    
        public int requisitionType_id { get; set; }
        public string name_type { get; set; }
        public string id_person { get; set; }
    
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual ICollection<requisition> requisition { get; set; }
    }
}
