//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_s
    {
        public int route_id { get; set; }
        public string nombre_bodega { get; set; }
        public string origin { get; set; }
        public string destination { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string load_download { get; set; }
        public string state { get; set; }
        public string employees_id { get; set; }
        public int order_cod { get; set; }
        public int client_id { get; set; }
    
        public virtual clients clients { get; set; }
        public virtual EMPLOYEES EMPLOYEES { get; set; }
        public virtual requisition requisition { get; set; }
    }
}
