//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_history
    {
        public string salesHistory_id { get; set; }
        public int client_id { get; set; }
        public string client_name { get; set; }
        public int bill_code { get; set; }
        public Nullable<System.DateTime> present_date { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public int product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> total_withTaxes { get; set; }
    
        public virtual bills bills { get; set; }
        public virtual clients clients { get; set; }
        public virtual products products { get; set; }
    }
}
