//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalePointEntities : DbContext
    {
        public SalePointEntities()
            : base("name=SalePointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accounts_payable> accounts_payable { get; set; }
        public DbSet<accounts_receivable> accounts_receivable { get; set; }
        public DbSet<bills> bills { get; set; }
        public DbSet<clients> clients { get; set; }
        public DbSet<EMPLOYEES> EMPLOYEES { get; set; }
        public DbSet<family_product> family_product { get; set; }
        public DbSet<products> products { get; set; }
        public DbSet<requisition> requisition { get; set; }
        public DbSet<requisition_type> requisition_type { get; set; }
        public DbSet<route_s> route_s { get; set; }
        public DbSet<sales_history> sales_history { get; set; }
        public DbSet<suppliers> suppliers { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
