//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalePointEntities : DbContext
    {
        public SalePointEntities()
            : base("name=SalePointEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accounts_payable> accounts_payable { get; set; }
        public DbSet<accounts_receivable> accounts_receivable { get; set; }
        public DbSet<bill> bill { get; set; }
        public DbSet<client> client { get; set; }
        public DbSet<detailBill> detailBill { get; set; }
        public DbSet<detailPurchaseOrder> detailPurchaseOrder { get; set; }
        public DbSet<detailRequisition> detailRequisition { get; set; }
        public DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public DbSet<family_product> family_product { get; set; }
        public DbSet<postType> postType { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<purchaseOrder> purchaseOrder { get; set; }
        public DbSet<requisition> requisition { get; set; }
        public DbSet<route> route { get; set; }
        public DbSet<supplier> supplier { get; set; }
    }
}
