//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class suppliers
    {
        public suppliers()
        {
            this.accounts_payable = new HashSet<accounts_payable>();
            this.products = new HashSet<products>();
        }
    
        public int supplier_id { get; set; }
        public string legalIdentification_card { get; set; }
        public string company { get; set; }
        public string company_account { get; set; }
        public string phone { get; set; }
        public string a_ddress { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<accounts_payable> accounts_payable { get; set; }
        public virtual ICollection<products> products { get; set; }
    }
}
